char: diagmem: Fix cast to smaller integer type
../drivers/char/diag/diagmem.c:184:11: error: cast to smaller integer type 'int' from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
                        size > (int)mempool->pool->pool_data) {
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Divyanshu-Modi <divyan.m05@gmail.com>
Signed-off-by: ElectroPerf <kunmun.devroms@gmail.com>
(cherry picked from commit 870cd61f333e9263330bbe438c1c57ce16905bd5)