qcacld-3.0: qdf_threads: fix compilation error with debug disabled
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/qdf/linux/src/qdf_threads.c:180:21: error:
      variable has incomplete type 'struct stack_trace'
        struct stack_trace trace = {
                           ^
../include/linux/stackdepot.h:26:8: note: forward declaration of 'struct stack_trace'
struct stack_trace;
       ^
1 error generated.

Signed-off-by: Yaroslav Furman <yaro330@gmail.com>
Signed-off-by: xiaoleGun <1592501605@qq.com>
(cherry picked from commit 2399bc3a427fb71ed28f9f9982c94f61f250c4d3)